baseURL = 'https://kakchouch.github.io/ometeotl/'
languageCode = 'en-us'
title = 'Ometeotl, an abstract decision meta-model'
theme = 'risotto'
defaultContentLanguage = 'en'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  [params.theme]
  palette = "ometeotl-solarized-light"

# Sidebar : about
[params.about]
title = "Ometeotl"
description = "A Python library to build complex multi-agent simulations, wargames, and AI-driven strategies"
logo_image = "/ometeotl/images/logo.png"

# Sidebar : social links
[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/kakchouch/ometeotl"

[[params.socialLinks]]
icon = "fa-solid fa-globe"
title = "Portfolio"
url = "https://akchouch.fr"

[languages]
  [languages.en]
    languageName = 'English'
    weight = 2
    contentDir = 'content/en'
    [[languages.en.menus.main]]
      name = 'Goals and specs'
      pageRef = '/goals_and_specs/'
      weight = 10
    [[languages.en.menus.main]]
      name = 'documentation'
      pageRef = '/documentation/'
      weight = 20
    [[languages.en.menus.main]]
      name = 'leaderboard'
      pageRef = '/leaderboard/'
      weight = 30
 
